# Generated by Django 3.2.5 on 2021-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
