# Generated by Django 3.2.5 on 2021-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20210711_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='pcs'),
        ),
    ]
